- name: Ensure kubectl configuration directory exists
  file:
    state: directory
    mode: 0700
    path: /root/.kube

- name: Configure kubectl on the host
  copy:
    src: "{{ kubernetes_kubeconfig_file }}"
    dest: /root/.kube/config
    remote_src: no
    mode: 0600
