- name: Répertoire de configuration kubectl
  file:
    state: directory
    mode: 0700
    path: /root/.kube

- name: Configure kubectl sur le serveur
  copy:
    src: "{{ k8s_kubeconfig }}"
    dest: /root/.kube/config
    remote_src: no
    mode: 0600
