- name: Get pki certificates and keys
  fetch:
    src: "{{ item }}"
    dest: "{{ role_path }}/files/pki/"
    flat: yes
  with_items:
    - /etc/kubernetes/pki/ca.crt
    - /etc/kubernetes/pki/ca.key
    - /etc/kubernetes/pki/sa.pub
    - /etc/kubernetes/pki/sa.key
    - /etc/kubernetes/pki/front-proxy-ca.crt
    - /etc/kubernetes/pki/front-proxy-ca.key
  delegate_to: "{{ groups['kubernetes_masters'][0] }}"
  run_once: yes
  changed_when: false # Local "buffer" must not notify any change. The changes if any will be notified by the copy

- name: Get etcd certificates
  fetch:
    src: "{{ item }}"
    dest: "{{ role_path }}/files/pki/etcd/"
    flat: yes
  with_items:
    - /etc/kubernetes/pki/etcd/ca.crt
    - /etc/kubernetes/pki/etcd/ca.key
  delegate_to: "{{ groups['kubernetes_masters'][0] }}"
  run_once: yes
  changed_when: false # Local "buffer" must not notify any change. The changes if any will be notified by the copy

- name: Ensure pki directory exists
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  with_items:
    - /etc/kubernetes/pki
    - /etc/kubernetes/pki/etcd

- name: Copy pki certificates and keys
  copy:
    src: "{{ role_path }}/files/pki/{{ item.src }}"
    dest: "/etc/kubernetes/pki/{{ item.src }}"
    mode: "{{ item.mode }}"
  with_items:
    - {src: "ca.crt", mode: "0644"}
    - {src: "ca.key", mode: "0600"}
    - {src: "sa.pub", mode: "0600"}
    - {src: "sa.key", mode: "0600"}
    - {src: "front-proxy-ca.crt", mode: "0644"}
    - {src: "front-proxy-ca.key", mode: "0600"}
    - {src: "etcd/ca.crt", mode: "0644"}
    - {src: "etcd/ca.key", mode: "0600"}

- name: Clean up local buffer
  file:
    state: absent
    path: "{{ role_path }}/files/pki"
  delegate_to: localhost
  run_once: yes
  changed_when: false
