- name: Get the node list
  k8s_info:
    kind: Node
    kubeconfig: "{{ kubernetes_kubeconfig_file }}"
  register: NodeList
  delegate_to: localhost

- name: Set the fact nodes for all play hosts
  set_fact:
    nodes: "{{ NodeList|json_query('resources[*].metadata.name') }}"
  with_items: "{{ play_hosts }}"
  delegate_to: "{{ item }}"
  run_once: yes

- name: Nodes present so far
  debug: var=nodes
