- name: Dépose la configuration d'initialisation kubeadm
  template:
    src: kubeadm_config.yaml.j2
    dest: /etc/kubeadm/config.yaml
    mode: 0755

- block:
  - name: Promets la présence du répertoire pki
    file:
      state: directory
      mode: 0755
      path: /etc/kubernetes/pki

  - name: Dépose les éléments de l'ac intermédiaire
    copy:
      src: "{{ item.src }}"
      dest: "/etc/kubernetes/pki/{{ item.dest }}"
      remote_src: no
      mode: "{{ item.mode }}"
    with_items:
      - dest: ca.crt
        src: "{{ kubernetes_pki.certificat }}"
        mode: "0644"
      - dest: ca.key
        src: "{{ kubernetes_pki.cle_privee }}"
        mode: "0600"
  when: kubernetes_pki is defined

- name: Dépose le bundle d'ac client
  copy:
    src: "{{ kubernetes_client_ca_file }}"
    dest: "/etc/kubernetes/pki/client_ca.pem"
    remote_src: no
    mode: "0644"
  when: kubernetes_client_ca_file is defined

- name: Vérifie si le master existe
  stat:
    path: /etc/kubernetes/admin.conf
  register: first_master

- name: Définis le fact already_initialized sur les hosts
  set_fact:
    already_initialized: "{{ first_master.stat.exists }}"
  with_items: "{{ play_hosts }}"
  delegate_to: "{{ item }}"
  run_once: yes

- name: Crée le premier noeud master
  command: "kubeadm init --config=/etc/kubeadm/config.yaml{%if node_name is defined %} --node-name {{ node_name }}{% endif %}"
  when: not already_initialized

- name: Récupère la configuration kubectl sur localhost
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ k8s_kubeconfig }}"
    flat: yes

- include_tasks: configure_kubectl.yml

# Hack : le wait de k8s_info skippe si la ressource n'existe pas...
- name: Attends le status OK du control plane
  k8s_info:
    kind: Pod
    name: "{{ item }}-{{ node_name | default(ansible_nodename) }}"
    namespace: kube-system
    kubeconfig: "{{ k8s_kubeconfig }}"
  register: result
  until: >-
    result.resources|length > 0
    and "containerStatuses" in result.resources[0].status
    and result.resources[0].status.containerStatuses|length > 0
    and result.resources[0].status.containerStatuses[0].ready
  retries: 10
  delay: 30
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  delegate_to: localhost
