- name: Vérifie si le master existe
  stat:
    path: /etc/kubernetes/admin.conf
  register: admin_config

- name: Crée le premier noeud master
  shell: "kubeadm init --config=/etc/kubeadm/config.yaml{%if node_name is defined %} --node-name {{node_name}}{% endif %}"
  when: not admin_config.stat.exists

- include_tasks: configure_kubectl.yml

- name: Récupère la configuration kubectl sur localhost
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{k8s_kubeconfig}}"
    flat: yes
  run_once: yes

# Hack : le wait de k8s_info skippe si la ressource n'existe pas...
- name: Attends le status OK du control plane
  k8s_info:
    kind: Pod
    name: "{{item}}-{{node_name | default(ansible_nodename)}}"
    namespace: kube-system
    kubeconfig: "{{k8s_kubeconfig}}"
  register: result
  until: 'result.resources|length > 0 and "containerStatuses" in result.resources[0].status and result.resources[0].status.containerStatuses|length > 0 and result.resources[0].status.containerStatuses[0].ready'
  retries: 10
  delay: 30
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  delegate_to: localhost
