- name: Vérifie si le master existe
  stat:
    path: /etc/kubernetes/admin.conf
  register: admin_config

- name: Crée le premier noeud master
  shell: "kubeadm init --config=/etc/kubeadm/config.yaml{%if node_name is defined %} --node-name {{node_name}}{% endif %}"
  when: not admin_config.stat.exists

- include_tasks: configure_kubectl.yml

- name: Récupère la configuration kubectl sur localhost
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{role_path}}/files/"
    flat: yes
  run_once: yes
