- name: Vérifie si le master existe
  stat:
    path: /etc/kubernetes/admin.conf
  register: admin_config

- name: Crée le noeud master
  shell: kubeadm init --config=/etc/kubeadm/config.yaml --upload-certs
  when: not admin_config.stat.exists
