- name: Récupère une join_command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  when: join_command is not defined
  delegate_to: "{{groups['kubernetes_masters'][0]}}"
  run_once: yes

- name: Mets a disposition la join_command
  set_fact:
    join_command: "{{ join_command_raw.stdout }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kubernetes_workers'] }}"
  when: join_command is not defined
  run_once: yes

- name: Affichage de la join_command
  debug: var=join_command

- name: Crée le noeud worker
  shell: "{{join_command}}{%if node_name is defined %} --node-name {{node_name}}{% endif %}"
