- include_tasks: get_join_params.yml

- name: Dépose la configuration join kubeadm
  template:
    src: kubeadm_join.yaml.j2
    dest: /etc/kubeadm/join_config.yaml
    mode: 0755

- name: Copie les certificats du control plane
  include_tasks: copy_certificates.yml
  when: '"kubernetes_masters" in group_names'

- name: Join le noeud au cluster
  command: "kubeadm join --config /etc/kubeadm/join_config.yaml"
  register: join
  changed_when: join.stdout_lines|length > 0

- block:
  - name: Attends le status OK du control plane
    k8s_info:
      kind: Pod
      name: "{{ item }}-{{ node_name | default(ansible_nodename) }}"
      namespace: kube-system
      kubeconfig: "{{ k8s_kubeconfig }}"
    register: result
    until: >-
      result.resources|length > 0
      and "containerStatuses" in result.resources[0].status
      and result.resources[0].status.containerStatuses|length > 0
      and result.resources[0].status.containerStatuses[0].ready
    retries: 10
    delay: 30
    with_items:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler
    delegate_to: localhost

  - include_tasks: configure_kubectl.yml

  when: '"kubernetes_masters" in group_names'
