---
- name: Pré-requis
  include_tasks: pre-requis.yml

- name: Définis l'api_endpoint
  set_fact:
    api_endpoint_tmp: "{{ kubernetes_control_plane_endpoint | default(ansible_fqdn)}}"
  delegate_to: "{{groups['kubernetes_masters'][0]}}"
  run_once: yes

- name: Mets a disposition l'api_endpoint'
  set_fact:
    api_endpoint: "{{ api_endpoint_tmp }}"
  delegate_to: "{{ item }}"
  with_items: "{{ play_hosts }}"
  run_once: yes

- name: Promets la présence du répertoire de configuration kubeadm
  file:
    state: directory
    path: /etc/kubeadm
    mode: 0755

- name: Dépose la configuration d'initialisation kubeadm
  template:
    src: kubeadm_config.yaml
    dest: /etc/kubeadm/config.yaml
  run_once: true
  delegate_to: "{{groups['kubernetes_masters'][0]}}"

- name: Installe le master
  include_tasks: init_master.yml
  when: '"kubernetes_masters" in group_names and inventory_hostname == groups["kubernetes_masters"][0]'

- name: Installe le cni
  include_tasks: cni.yml

- name: Récupère les nodes
  include_tasks: get_nodes.yml
  run_once: yes

- name: Join les masters supplémentaires
  include_tasks: join_master.yml
  when: '"kubernetes_masters" in group_names and inventory_hostname != groups["kubernetes_masters"][0] and node_name|default(ansible_fqdn) not in nodes'

- name: Join les workers
  include_tasks: join_worker.yml
  when: '"kubernetes_workers" in group_names and node_name | default(ansible_fqdn) not in nodes'
