---
- name: Pré-requis
  include_tasks: pre-requis.yml

- name: Promets la présence du répertoire de configuration kubeadm
  file:
    state: directory
    path: /etc/kubeadm
    mode: 0755
  run_once: true
  delegate_to: "{{groups['kubernetes_masters'][0]}}"

- name: Dépose la configuration kubeadm
  template:
    src: kubeadm_config.yaml
    dest: /etc/kubeadm/config.yaml
  run_once: true
  delegate_to: "{{groups['kubernetes_masters'][0]}}"

- name: Installe le master
  include_tasks: installe_master.yml
  when: '"kubernetes_masters" in group_names'
