- name: Dépose la configuration yum
  template:
    src: "{{item}}"
    dest: "/etc/yum.repos.d/"
    mode: 0644
  with_fileglob:
    - "../templates/*.repo"

- name: Installation des paquets kubernetes
  yum:
    name:
      - kubelet-{{kubernetes_version}}
      - kubeadm-{{kubernetes_version}}
      - kubectl-{{kubernetes_version}}
      - iptables-services
    enablerepo: kubernetes
    state: present

- name: Applique les paramètres sysctl
  sysctl:
    name: "{{item}}"
    value: '1'
    state: present
    sysctl_file: "/etc/sysctl.d/k8s.conf"
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
