- name: Configure yum
  template:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/"
    mode: 0644
  with_fileglob:
    - "../templates/*.repo"

- name: Check kubeadm package status
  yum: list=kubeadm
  register: kubeadm_package

- name: Install kubernetes packages
  yum:
    name:
      - kubelet-{{ kubernetes_version }}
      - kubeadm-{{ kubernetes_version }}
      - kubectl-{{ kubernetes_version }}
      - iptables-services
    enablerepo: kubernetes
    state: present
  when: 'kubeadm_package.results|length == 0 or kubeadm_package.results[0].yumstate != "installed"'





- name: Set sysctl parameters required by kubernetes
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    sysctl_file: "/etc/sysctl.d/k8s.conf"
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

- name: Ensure ipvs kernel modules are loadable
  modprobe:
    name: "{{ item }}"
  with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
  when: kubernetes_proxy_mode == "ipvs"

- name: Install IPSet package
  yum:
    name: ipset
    state: present
  when: kubernetes_proxy_mode == "ipvs"
