---
dependency:
  name: galaxy
  options:
    role-file: molecule/commun/requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: master
    box: centos/7
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_masters
      - kubernetes
  - name: worker1
    box: centos/7
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_workers
      - kubernetes
  - name: worker2
    box: centos/7
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_workers
      - kubernetes
provisioner:
  name: ansible
  env:
    DOCKER_REGISTRY_MIRROR: ${DOCKER_REGISTRY_MIRROR}
    QUAY_REGISTRY_MIRROR: ${QUAY_REGISTRY_MIRROR}
    K8S_REGISTRY_MIRROR: ${K8S_REGISTRY_MIRROR}
    INSECURE_REGISTRIES: ${INSECURE_REGISTRIES}
    CENTOS_BASE_MIRROR: ${CENTOS_BASE_MIRROR}
    DOCKER_YUM_MIRROR: ${DOCKER_YUM_MIRROR}
    K8S_YUM_MIRROR: ${K8S_YUM_MIRROR}
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      master:
        node_name: master1
        docker_repo: ${DOCKER_YUM_MIRROR}
      worker1:
        node_name: worker1
        docker_repo: ${DOCKER_YUM_MIRROR}
      worker2:
        node_name: worker2
        docker_repo: ${DOCKER_YUM_MIRROR}
verifier:
  name: testinfra
  directory: ../commun/tests/
  lint:
    name: flake8
  options:
    hosts: master,worker1,worker2
