---
- name: Converge masters
  hosts: kubernetes_masters
  tasks:
    - name: "Include kubernetes-bare-metal"
      include_role:
        name: "kubernetes-bare-metal"
      vars:
        kubernetes_version: 1.19.3
        kubernetes_control_plane_endpoint: lb

- name: Converge workers
  hosts: kubernetes_workers
  tasks:
    - name: "Include kubernetes-bare-metal"
      include_role:
        name: "kubernetes-bare-metal"
      vars:
        kubernetes_version: 1.19.3
        kubernetes_control_plane_endpoint: lb
        kubernetes_upgrade_consistency_check: false
