---
- name: Converge masters
  hosts: kubernetes_masters
  tasks:
    - name: "Include kubernetes-bare-metal"
      include_role:
        name: "kubernetes-bare-metal"
      vars:
        kubernetes_version: 1.19.2
        kubernetes_control_plane_endpoint: lb
        kubernetes_image_repository: 10.0.4.40:5001
        flannel_image: 10.0.4.40:5002/coreos/flannel
        metrics_server_image: 10.0.4.40:5001/metrics-server/metrics-server
        centos:
          kubernetes:
            repo: http://10.0.4.40:8081/repository/kube-yum/

- name: Converge workers
  hosts: kubernetes_workers
  tasks:
    - name: "Include kubernetes-bare-metal"
      include_role:
        name: "kubernetes-bare-metal"
      vars:
        kubernetes_version: 1.19.2
        kubernetes_control_plane_endpoint: lb
        kubernetes_upgrade_consistency_check: false
        kubernetes_image_repository: 10.0.4.40:5001
        flannel_image: 10.0.4.40:5002/coreos/flannel
        metrics_server_image: 10.0.4.40:5001/metrics-server/metrics-server
        centos:
          kubernetes:
            repo: http://10.0.4.40:8081/repository/kube-yum/
