---
dependency:
  name: galaxy
  options:
    role-file: molecule/commun/requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: lb
    box: centos/7
    memory: 1024
    cpus: 1
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - loadbalancer
  - name: master1
    box: debian/buster64
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_masters
      - kubernetes
      - docker
  - name: master2
    box: debian/buster64
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_masters
      - kubernetes
      - containerd
  - name: master3
    box: centos/7
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_masters
      - kubernetes
      - containerd
  - name: worker1
    box: centos/7
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_workers
      - kubernetes
      - containerd
  - name: worker2
    box: debian/buster64
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_workers
      - kubernetes
      - docker
provisioner:
  name: ansible
  env:
    CONTAINERD_REGISTRY_MIRRORS: ${CONTAINERD_REGISTRY_MIRRORS}
    DOCKER_REGISTRY_MIRROR: ${DOCKER_REGISTRY_MIRROR}
    QUAY_REGISTRY_MIRROR: ${QUAY_REGISTRY_MIRROR}
    K8S_REGISTRY_MIRROR: ${K8S_REGISTRY_MIRROR}
    INSECURE_REGISTRIES: ${INSECURE_REGISTRIES}
    CENTOS_BASE_MIRROR: ${CENTOS_BASE_MIRROR}
    DOCKER_YUM_MIRROR: ${DOCKER_YUM_MIRROR}
    K8S_YUM_MIRROR: ${K8S_YUM_MIRROR}
    K8S_APT_MIRROR: ${K8S_APT_MIRROR}
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      master1:
        node_name: master1
        containerd_repo: ${DOCKER_YUM_MIRROR}
      master2:
        node_name: master2
        containerd_repo: ${DOCKER_YUM_MIRROR}
      master3:
        node_name: master3
        containerd_repo: ${DOCKER_APT_MIRROR}
      worker1:
        node_name: worker1
        containerd_repo: ${DOCKER_YUM_MIRROR}
      worker2:
        node_name: worker2
        containerd_repo: ${DOCKER_APT_MIRROR}
verifier:
  name: testinfra
  directory: ../commun/tests/
  lint:
    name: flake8
  options:
    hosts: master1,master2,master3,worker1,worker2
