---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: lb
    box: centos/7
    memory: 1024
    cpus: 1
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - loadbalancer
  - name: master1
    box: centos/7
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_masters
      - kubernetes
  - name: master2
    box: centos/7
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_masters
      - kubernetes
  - name: master3
    box: centos/7
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_masters
      - kubernetes
  - name: worker1
    box: centos/7
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_workers
      - kubernetes
  - name: worker2
    box: centos/7
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_workers
      - kubernetes
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      master:
        node_name: master1
      worker1:
        node_name: worker1
      worker2:
        node_name: worker2
verifier:
  name: testinfra
  directory: ../commun/tests/
  lint:
    name: flake8
  options:
    hosts: master1,master2,master3,worker1,worker2
