---
- name: KVM hosts
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Installe les pré-requis python pour k8s
      pip:
        executable: /usr/bin/pip3
        name:
          - openshift>=0.6
          - PyYAML>=3.11
          - jmespath

- name: Prepare k8s hosts
  hosts: kubernetes
  gather_facts: true
  tasks:
    - name: Dépose la configuration yum
      copy:
        content: |
          [base]
          name=CentOS-$releasever - Base
          baseurl=http://10.0.4.40:8081/repository/centos-base/centos/$releasever/os/$basearch/
          gpgcheck=0

          [updates]
          name=CentOS-$releasever - Updates
          baseurl=http://10.0.4.40:8081/repository/centos-base/centos/$releasever/updates/$basearch/
          gpgcheck=0

          [extras]
          name=CentOS-$releasever - Extras
          baseurl=http://10.0.4.40:8081/repository/centos-base/centos/$releasever/extras/$basearch/
          gpgcheck=0
        dest: /etc/yum.repos.d/CentOS-Base.repo
        mode: 0755


    - name: Crée le répetoire de configuration docker
      file:
        state: directory
        path: /etc/docker
        mode: 0755

    - name: Configure docker
      copy:
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
              "insecure-registries" : ["10.0.4.40:5000", "10.0.4.40:5001", "10.0.4.40:5002"],
              "registry-mirrors": ["https://10.0.4.40:5000"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2",
            "storage-opts": [
              "overlay2.override_kernel_check=true"
            ]
          }
        dest: /etc/docker/daemon.json
        mode: 0755

    - name: Configure le repo yum
      copy:
        content: |
          [docker-ce-stable]
          name=Docker CE Stable - $basearch
          baseurl=http://10.0.4.40:8081/repository/docker-yum/$releasever/$basearch/stable
          enabled=1
          gpgcheck=0
        dest: /etc/yum.repos.d/docker.repo
        mode: 0755

    - name: "Install docker"
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: "Disable swap"
      command: swapoff -a -v
      register: swapoff
      changed_when: swapoff.stdout_lines|length > 0

    - name: Disable SWAP in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+.*)$'
        replace: '# \1'

- name: Prepare haProxy nodes
  hosts: loadbalancer
  gather_facts: true
  tasks:
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive

    - name: Disable firewalld
      systemd:
        name: firewalld
        enabled: no
        state: stopped

    - name: Flush existing iptables rules
      iptables:
        flush: yes

    - name: List load balanced items
      set_fact:
        apiServers: "{{ apiServers | default([]) + [{'name': item, 'address': item + ':6443'}] }}"
      with_items: "{{ groups['kubernetes_masters'] }}"

    - name: "Print apiServers loadbalanced"
      debug: var=apiServers

    - name: "Install HaProxy"
      include_role:
        name: "geerlingguy.haproxy"
      vars:
        haproxy_frontend_name: 'apiServer'
        haproxy_frontend_port: 6443
        haproxy_frontend_mode: 'tcp'
        haproxy_backend_name: 'apiServerBackend'
        haproxy_backend_mode: 'tcp'
        haproxy_backend_httpchk: ''
        haproxy_backend_servers: "{{ apiServers }}"
