---
- name: Converge
  hosts: all
  tasks:
    - name: "Include kubernetes-bare-metal"
      include_role:
        name: "kubernetes-bare-metal"
      vars:
        metrics_server_wait_deploy: false
        kubernetes_image_repository: docker-k8s-gcr-proxy.repository.pole-emploi.intra
        flannel_image: docker-quay-proxy.repository.pole-emploi.intra/coreos/flannel
        metrics_server_image: docker-k8s-gcr-proxy.repository.pole-emploi.intra/metrics-server/metrics-server
        centos:
          kubernetes:
            repo: https://repository.pole-emploi.intra/artifactory/rpm-kubernetes-proxy/
