---
- name: Converge
  hosts: all
  tasks:
    - name: "Include kubernetes-bare-metal"
      include_role:
        name: "kubernetes-bare-metal"
      vars:
        metrics_server_wait_deploy: false
        kubernetes_image_repository: "{{ lookup('env', 'K8S_REGISTRY_MIRROR') }}"
        flannel_image: "{{ lookup('env', 'QUAY_REGISTRY_MIRROR') }}/coreos/flannel"
        metrics_server_image: "{{ lookup('env', 'K8S_REGISTRY_MIRROR') }}/metrics-server/metrics-server"
        kubernetes_yum_repo: "{{ lookup('env', 'K8S_YUM_MIRROR') }}"
