---
dependency:
  name: galaxy
  options:
    role-file: requirements-molecule.yaml
driver:
  name: vagrant
  provider:
    name: libvirt
    # type: libvirt
platforms:
  - name: master
    # box: fedora/32-cloud-base
    box: centos/7
    memory: 2048
    cpus: 2
    provider_options:
      connect_via_ssh: true
    provider_raw_config_args:
      - 'host="kvm"'
      - 'username="libvirt-user"'
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_masters
      - kubernetes
provisioner:
  name: ansible
  config_options:
    ssh_connection:
      ssh_args: -o ControlMaster=auto -o ControlPersist=60s -o ProxyCommand="ssh -W %h:%p -q -l libvirt-user kvm"
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      master:
        node_name: master1
verifier:
  name: testinfra
  directory: ../commun/tests/
  lint:
    name: flake8
  options:
    ssh-config: ../sommun/tests/ssh_config
    hosts: master
