---
dependency:
  name: galaxy
  options:
    role-file: requirements-molecule.yaml
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: master
    box: centos/7
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - kubernetes_masters
      - kubernetes
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      master:
        node_name: master1
verifier:
  name: testinfra
  directory: ../commun/tests/
  lint:
    name: flake8
  options:
    hosts: master
