- name: Récupère les informations des nodes
  k8s_info:
    kind: Node
    kubeconfig: "{{k8s_kubeconfig}}"
  register: node_list_version
  delegate_to: localhost

- name: Liste les versions de nodes en cours d'execution
  set_fact:
    nodes_versions: "{{node_list_version|json_query('resources[*].status.nodeInfo.kubeletVersion')|unique|sort}}"

- name: Vérifie la cohérence des versions du cluster
  assert:
    that:
      - nodes_versions|length == 1
    fail_msg: "Cluster incohérent! plusieurs versions trouvées sur les nodes"
    success_msg: "Cluster cohérent"
  when: kubernetes_upgrade_consistency_check

- name: Définis la version courante globale du cluster
  set_fact:
    cluster_version: "{{ nodes_versions[0] | regex_replace('^v') }}"

- name: Récupère la version de kubeadm disponible
  yum:
    list: kubeadm
  register: kubeadm_package

- name: Définis le besoin d'upgrade du cluster
  set_fact:
    need_upgrade: "{% if cluster_version != kubeadm_package.results[0].version %}{{true}}{% else %}{{false}}{% endif %}"

- name: Définis le fact sur le reste des hosts du play
  set_fact:
    need_upgrade: "{{ need_upgrade }}"
  delegate_to: "{{ item }}"
  with_items: "{{ play_hosts }}"
  run_once: yes

- name: Affiche le résultat
  debug: var=need_upgrade
