- name: Update kubelet and kubectl
  yum:
    name:
      - kubelet-{{ kubernetes_version }}
      - kubectl-{{ kubernetes_version }}
    enablerepo: kubernetes
    state: present

- name: Restart kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
    state: restarted
