- name: Update kubelet and kubectl (RHEL)
  yum:
    update_cache: true
    name:
      - kubelet-{{ kubernetes_version }}
      - kubectl-{{ kubernetes_version }}
    enablerepo: kubernetes
    state: present
  when: 'ansible_os_family == "RedHat"'

- name: Update kubelet and kubectl (deb)
  apt:
    update_cache: true
    name:
      - kubelet={{ kubernetes_version }}-00
      - kubectl={{ kubernetes_version }}-00
    state: present
  when: 'ansible_os_family == "Debian"'

- name: Restart kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
    state: restarted
