apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: {{environnement}}
kubernetesVersion: {{ kubernetes_version }}
networking:
  podSubnet: "{{ kubernetes_pod_subnet | default(kubernetes_default_pod_cidr) }}"
controlPlaneEndpoint: {{k8s_fqdn_api}}
# etcd:
#   local:
#     dataDir: /var/lib/etcd
imageRepository: {{ kubernetes_image_repository | default("k8s.gcr.io")}}
