apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: {{kubernetes_cluster_name}}
kubernetesVersion: {{ kubernetes_version }}
networking:
  podSubnet: "{{ kubernetes_pod_subnet | default(kubernetes_default_pod_cidr) }}"
controlPlaneEndpoint: {{ kubernetes_control_plane_endpoint | default(ansible_fqdn)}}
# etcd:
#   local:
#     dataDir: /var/lib/etcd
imageRepository: {{ kubernetes_image_repository | default("k8s.gcr.io")}}
